[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F -d listen=127.0.0.1:9000
environment=MYSQLHOST="%(ENV_MYSQLHOST)s",MYSQLPORT="%(ENV_MYSQLPORT)s",MYSQLDATABASE="%(ENV_MYSQLDATABASE)s",MYSQLUSER="%(ENV_MYSQLUSER)s",MYSQLPASSWORD="%(ENV_MYSQLPASSWORD)s",APP_ENV="%(ENV_APP_ENV)s",RESEND_API_KEY="%(ENV_RESEND_API_KEY)s",MAIL_FROM="%(ENV_MAIL_FROM)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
environment=PORT="%(ENV_PORT)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true