[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F -d listen=127.0.0.1:9000
environment=MYSQLHOST="%(env:MYSQLHOST)s",MYSQLPORT="%(env:MYSQLPORT)s",MYSQLDATABASE="%(env:MYSQLDATABASE)s",MYSQLUSER="%(env:MYSQLUSER)s",MYSQLPASSWORD="%(env:MYSQLPASSWORD)s",APP_ENV="%(env:APP_ENV)s",RESEND_API_KEY="%(env:RESEND_API_KEY)s",MAIL_FROM="%(env:MAIL_FROM)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
environment=PORT="%(env:PORT)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
